### ISSUE TITLE
Adaptation for rclc-executor

### ISSUE THREAD

**Issue by JanStaschulat** [ros-realtime/reference-system#53]
All nodes are inherited from `rclcpp::Node` and then publishers and subscriptions are created. I would like to replace e.g. the [Fusion node](https://github.com/ros-realtime/reference-system/blob/a22d9ee83eebf653f0bb2f94f922f1d0e44d55b8/reference_system/include/reference_system/nodes/rclcpp/fusion.hpp#L31)

`class Fusion : public rclcpp::Node`
by
`class Fusion `

Inside the class Fusion, I will then use the C-API from rclc package to create nodes, subscriptions and publishers as necessary.
Does the reference system (building the autoware_auto setup, tracing tools etc. ) rely on the fact, that a `node` is always an `rclcpp::Node`? I am asking this, because for the rclc-executor use-case there will be no `rclcpp::Node` available. 
(I will replace, of course, the code that adds nodes to the executor by adding the callbacks of subscriptions directly to the rclc-executor).

**Comment by christophebedard** [comment]
@JanStaschulat @flynneva as for the tracing instrumentation, I looked into it and quickly put something together: https://github.com/christophebedard/rclc/tree/christophebedard/add-temporary-instrumentation-with-tracetools. It uses the `rclcpp` instrumentation so that it *seems* like it's `rclcpp`. It's really a hack, but this way we don't need to modify `tracetools` (or define new tracepoints for `rclc`) or `tracetools_analysis`* and hopefully we save a bunch of time.

*we do need to modify `tracetools_analysis` because `rclc` doesn't link timers to nodes, so some of the utility code that relies on that needs to be changed to be more lenient:

diff --git a/tracetools_analysis/tracetools_analysis/utils/ros2.py b/tracetools_analysis/tracetools_analysis/utils/ros2.py
index 13f69f7..d61380d 100644
--- a/tracetools_analysis/tracetools_analysis/utils/ros2.py
+++ b/tracetools_analysis/tracetools_analysis/utils/ros2.py
@@ -321,7 +321,8 @@ class Ros2DataModelUtil(DataModelUtil):
         node_handle = self.data.timer_node_links.loc[timer_handle, 'node_handle']
         node_handle_info = self.get_node_handle_info(node_handle)
         if node_handle_info is None:
-            return None
+            # return None
+            node_handle_info = {}
 
         tid = self.data.timers.loc[timer_handle, 'tid']
         period_ns = self.data.timers.loc[timer_handle, 'period']

This line in #49 probably won't work either, since the node name (`'FrontLidarDriver'`) won't be in the string: https://github.com/ros-realtime/reference-system/blob/a460b954930845503561a1b0d1bde8b62265bd4f/autoware_reference_system/test/dropped_messages.py#L159. However, we can infer the node instead by comparing the tid of the timers (from the `Ros2DataModel.timers` `pandas.DataFrame`) to the node tids (from the `Ros2DataModel.nodes` `pandas.DataFrame`) in the dropped message analysis code.

Otherwise it does work. I ran the `example_pingpong` example from `rclc_examples`:

```
# Terminal 1 (press enter to start tracing, run the example, then press enter again to stop tracing)
ros2 trace --session-name rclc-pingpong -k
# Terminal 2
ros2 run rclc_examples example_pingpong
```

and I get this when running the trace through the [callback duration example notebook/analysis](https://gitlab.com/ros-tracing/tracetools_analysis/-/blob/master/tracetools_analysis/analysis/callback_duration.ipynb):

![Screenshot from 2021-10-13 21-07-55](https://user-images.githubusercontent.com/3717345/137233633-d1796247-a2ec-4f5f-a4df-bf8cf365cfc9.png)

**Comment by christophebedard** [comment]
> because `rclc` doesn't link timers to nodes

Or we can call the tracepoint to manually link timers to the right nodes in the `rclc`-specific part of the reference system. Then we can avoid needing to modify `tracetools_analysis` and the dropped message analysis code.

**Comment by flynneva** [comment]
closing after #73, feel free to reopen if desired
